### ISSUE TITLE
no such file or directory: 'PolicyIdMap.json'

### ISSUE THREAD

**Issue by tkishel** [tkishel/pc-toolbox#1]
PolicyIdMap.json is referenced in pc-compliance-import.py and pc-policy-custom-import.py,
but not in any of the export scripts ...

**Comment by jdrieger** [comment]
Oh, yea, I ran into this with Adam.  So, in the importer, one of the contributors added in the ability to import custom policies and have compliance map to them.  This was a nice enhancement, but the changed code now expects that file to exist regardless of custom policy or not.  So there are 2 use cases:

1. If you have custom policies you want mapped, you need to first run the pc-policy-custom-import.py, which will generate that file when it does the import from your previously exported custom policies (pc-policy-custom-export.py).  Then you can run the pc-policy-custom-import.py.
2. If you do NOT have custom policies you want mapped, just create a dummy file with the name of "PolicyIdMap.json" and a contents of ```{"placeholder":"file"}```

At some point there needs to be a switch implemented that can determine if custom policy is needed, but for now, that is the workaround.

**Comment by tkishel** [comment]
Resolved by recent commits adding a check for the file and command-line arguments for the functionality.
