### ISSUE TITLE
Feature Request: pc-user-update.py add the ability to enable/disable API

### ISSUE THREAD

**Issue by john-lowry** [tkishel/pc-toolbox#10]
I have a large-ish set of users created with `pc-user-import.py` and now we have decided to give them API access. I wondering if it would be possible to update `pc-user-update.py` and `pc-user-import.py` with the ability to enable and disable API access for users.

**Comment by tkishel** [comment]
This commit addresses setting `accessKeysAllowed` on import or update ...

https://github.com/tkishel/pc-toolbox/commit/e3cb7f13496672963cd8b410273bd2133461182a

... if that is what you meant by "API access".

But if you meant managing API access via permissions, then you would do that by specifying the appropriate role.

Note that I've renamed the `-r/--role` command-line parameters in `pc-user-update.py` to match `pc-user-import.py`.

Please verify and close, or let me know if this does not resolve this request!

**Comment by john-lowry** [comment]
Yes, that is what I meant by API. In the console it is a radio button, just wanted something to toggle it on when creating users or updating users.

**Comment by tkishel** [comment]
Great! I've just pushed a lot of changes to correct issues caught by pylint, so I suggest pulling again.
